# Generated by Django 4.2.11 on 2024-03-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0002_company_employee_devicelog_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="check_out_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="returned_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="check_out_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="returned_date",
            field=models.DateTimeField(null=True),
        ),
    ]
