# Generated by Django 4.2.11 on 2024-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0003_alter_device_check_out_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="check_out_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="returned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="check_out_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="returned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
