# Generated by Django 4.2.11 on 2024-03-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0004_alter_device_check_out_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicelog",
            name="device_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="assignment.device",
            ),
        ),
    ]
